# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 748a8b39a2dd467ad54f1ca92ece5e873a037d0d112460cf98ffd7303002cc6de6dec2513e9e31e3d262e34aca2fbede41bae2ca65428d692856ea3438cd7187

test:
  secret_key_base: 31bac890470b085615dd4aa2f73e6181cbea0a3484b4c457a769b3a0078aec1f910024de3ee7bc4788c55d13dface5e486b3b146439f0f6c666a270e506d505a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
